# Generated by Django 5.0.4 on 2024-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='content',
            field=models.TextField(),
        ),
    ]
