# Generated by Django 5.0.4 on 2024-05-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_alter_visitor_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='eamil',
            new_name='email',
        ),
    ]
